In [2]:
import pandas as pd
data = pd.read_csv("D:\downloads_new\customer_shopping_behavior_dataset.csv")
data.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [3]:
data.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [5]:
data.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
data.shape

(3900, 18)

In [7]:
data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
# Fill missing Review Ratings with the median rating of their own category
# This is smarter than using a global median since different categories may have different rating patterns
# lambda x represents each category group passed in one at a time by groupby
data['Review Rating'] = data.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
# Convert column names to sanke case (lowercase and replace spaces with underscores)
data.columns = data.columns.str.lower()
data.columns = data.columns.str.replace(' ', '_')
#Renaming Column
data.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'}, inplace = True)

In [11]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [13]:
# Divide age into 4 equal groups based on data distribution using quantile-based binning
# pd.qcut splits data into q=4 equal sized buckets (each containing 25% of the data)
# Labels assigned: Young Adult, Adult, Middle Aged, Senior
labels = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']
data['age_group'] = pd.qcut(data['age'], q=4, labels=labels)

In [14]:
data[['age','age_group']].head(10)

   age    age_group
0   55  Middle Aged
1   19  Young Adult
2   50  Middle Aged
3   21  Young Adult
4   45  Middle Aged
5   46  Middle Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle Aged

In [15]:
# Convert text-based purchase frequency into numeric days for easier analysis
# e.g. 'Weekly' → 7, 'Monthly' → 30, 'Annually' → 365
# .map() replaces each value in the column using the dictionary lookup
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

data['purchase_frequency_days'] = data['frequency_of_purchases'].map(frequency_mapping)

In [16]:
data[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [17]:
data[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [18]:
#Check if the values are actually same in discount_applied and promo_code_used
(data['discount_applied'] == data['promo_code_used']).all()

np.True_

In [19]:
# Dropping promo_code_used column
# axis = 1 means dropping column.
# axis = 0 means dropping rows
data = data.drop('promo_code_used', axis=1)

In [20]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [21]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\rabin\appdata\local\programs\python\python311\lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\rabin\appdata\local\programs\python\python311\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\users\rabin\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rabin\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## Loading Cleaned Data into MySQL

After cleaning, the dataset was exported from the pandas DataFrame into a MySQL database for SQL-based analysis, using SQLAlchemy and PyMySQL as the connector.

**Approach:**
- Established a connection using `sqlalchemy.create_engine()` with a MySQL/PyMySQL connection string
- Wrote the cleaned DataFrame to a MySQL table using `DataFrame.to_sql()`, with `if_exists="replace"` to allow re-runs during development
- Verified the load with a `SELECT * FROM customer LIMIT 5` query read back via `pandas.read_sql()`

```python
from sqlalchemy import create_engine

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
data.to_sql("customer", engine, if_exists="replace", index=False)
```

*(Credentials omitted here for security — see `sql/customer_shopping_behavior.sql` for the full set of analytical queries run against this table.)*

In [24]:
from sqlalchemy import create_engine

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
data.to_sql("customer", engine, if_exists="replace", index=False)

3900